api_platform:
  defaults:
    pagination_enabled: false
  path_segment_name_generator: 'App\ApiOperation\ApiPatchSegmentNameGenerator'
  mapping:
    paths: [ '%kernel.project_dir%/App/Entity' ]
  patch_formats:
    json: [ 'application/merge-patch+json' ]
  swagger:
    versions: [ 3 ]
    api_keys:
      apiKey:
        name: Authorization
        type: header
