services:
  memcached:
    container_name: memcached_php_sf_playground_container
    image: 'memcached:alpine'
    ports:
      - '7001:11211'

  redis:
    container_name: redis_php_sf_playground_container
    image: 'redis:alpine'
    ports:
      - '7002:6379'

  postgres:
    container_name: postgres_php_sf_playground_container
    image: 'postgres:16-alpine'
    working_dir: /application
    volumes:
      - '.:/application'
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=php-sf-playground-db-postgresql
    ports:
      - '7003:5432'

  rabbitmq:
    container_name: rabbitmq_php_sf_playground_container
    image: 'rabbitmq:latest'
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    ports:
      - '7004:5672'

  mysql:
    container_name: mysql_php_sf_playground_container
    image: 'mysql:latest'
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=php-sf-playground-db-mysql
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    ports:
      - '7005:3306'

  mariadb:
    container_name:    mariadb_php_sf_playground_container
    image: 'mariadb:latest'
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=php-sf-playground-db-mariadb
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    ports:
      - '7006:3306'

  selenium:
    container_name: selenium_php_sf_playground_container
    image: 'selenium/standalone-firefox:latest'
    ports:
      - '4444:4444'
      - '7900:7900'
    shm_size: '2gb'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
