"use strict";

const path = require( "path" );
const Dotenv = require( "dotenv-webpack" );
const TerserPlugin = require( "terser-webpack-plugin" );
const JavaScriptObfuscator = require( "webpack-obfuscator" );
const { CleanWebpackPlugin } = require( "clean-webpack-plugin" );
const { WebpackManifestPlugin } = require( "webpack-manifest-plugin" );
const dotenv = require( "dotenv" );

module.exports = ( env ) => {
  dotenv.config();
  const isProduction = env.mode === "production";

  return {
    mode: env.mode,
    entry: { app: "./src/index.js" },
    cache: Boolean( env.cache ),
    devtool: isProduction ? false : "inline-source-map",

    performance: {
      hints: isProduction ? false : "warning",
    },

    optimization: {
      minimize: isProduction,
      minimizer: [
        isProduction &&
        new TerserPlugin( {
          parallel: true,
          terserOptions: {
            format: {
              comments: false,
            },
            compress: {
              drop_console: true,
            },
          },
          extractComments: false,
        } ),
      ].filter( Boolean ),
    },

    output: {
      filename: isProduction
        ? `[name].[contenthash].js`
        : "app.js",
      path: path.resolve( __dirname, "public/build" ),
      library: "app",
    },

    watchOptions: {
      aggregateTimeout: 100,
    },

    plugins: [
      new CleanWebpackPlugin( {
        cleanStaleWebpackAssets: false, // Prevent removing files not generated by this webpack build
        cleanOnceBeforeBuildPatterns: [
          "**/*",
          "!bootstrap.min.js",
          "!jquery-3.6.0.min.js",
        ],
      } ),
      isProduction && new WebpackManifestPlugin( { publicPath: '/build/' } ),
      isProduction && new JavaScriptObfuscator( {
        domainLock: [
          'localhost',
          '127.0.0.1:7000',
          'nations-original.com',
        ],
        debugProtection: true,
        debugProtectionInterval: 4000,  // re-triggers debugger every 4s — devtools unusable
        disableConsoleOutput: true,
        compact: true,
        controlFlowFlattening: true,
        controlFlowFlatteningThreshold: 0.75,
        deadCodeInjection: true,
        deadCodeInjectionThreshold: 0.4,
        identifierNamesGenerator: 'hexadecimal',
        log: false,
        numbersToExpressions: true,
        renameGlobals: false,
        selfDefending: true,
        simplify: true,
        splitStrings: true,
        splitStringsChunkLength: 5,
        stringArray: true,
        stringArrayCallsTransform: true,
        stringArrayCallsTransformThreshold: 0.75,
        stringArrayEncoding: [ 'rc4' ],
        stringArrayIndexShift: true,
        stringArrayRotate: true,
        stringArrayShuffle: true,
        stringArrayWrappersCount: 2,
        stringArrayWrappersChainedCalls: true,
        stringArrayWrappersParametersMaxCount: 4,
        stringArrayWrappersType: 'function',
        stringArrayThreshold: 0.75,
        unicodeEscapeSequence: false,
      } ),
    ].filter( Boolean ),

    module: {
      rules: [
        {
          test: /\.s[ac]ss$/i,
          use: [
            "style-loader",
            "css-loader",
            "sass-loader",
          ],
        },
      ],
    },
    resolve: {
      extensions: [ ".js" ]
    },
  };
};
