doctrine:
  dbal:
    url: '%env(resolve:DATABASE_URL)%'
    driver_class: PHP_SF\System\Database\DoctrineEntityManager
  orm:
    auto_generate_proxy_classes: false
    query_cache_driver:
      type: pool
      pool: doctrine.system_cache_pool
    result_cache_driver:
      type: pool
      pool: doctrine.result_cache_pool

framework:
  cache:
    pools:
      doctrine.result_cache_pool:
        adapter: cache.app
      doctrine.system_cache_pool:
        adapter: cache.system
